apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
      - name: ml-model
        image: <account_id>.dkr.ecr.<region>.amazonaws.com/ml-model-api:latest
        ports:
        - containerPort: 8000
